POST http://localhost:5077/api/Otp/generate
Content-Type: application/json

{
  "username": "andrei"
}
###
POST http://localhost:5077/api/Otp/verify
Content-Type: application/json

{
  "username": "andrei",
  "otp": "901987"
}
###
